### ISSUE TITLE
SET_Z_FROM_PROBE_ACCURACY

### ISSUE THREAD

**Issue by rainman19121979** [vvuk/sv08-config#1]
The first thing I would like to say is that I think your configuration is brilliant, but unfortunately something seems to be missing, I always get the following error when homeing:

Error evaluating 'gcode_macro SET_Z_FROM_PROBE_ACCURACY:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'last_accuracy_result'

I would be grateful for tips.

I adapted everything to my printer (SV08).

**Comment by vvuk** [comment]
Yep, you would have also needed to apply a klipper patch -- but I've actually just reworked things to go back to similar how BTT suggests via PROBE but instead upping the number of probe samples. Still using SET_KINEMATIC_POSITION though. I've pushed (an updated eddy.cfg)[https://github.com/vvuk/sv08-config/blob/main/eddy.cfg] and you can see what changed here: https://github.com/vvuk/sv08-config/commit/21a962185bb0c721265e69c1d69275ebb5cdfab4
